version: '2'

services:

  main:
    depends_on:
      - db
    image: wonderfall/nextcloud
    links:
      - db:db_nextcloud
    environment:
      - UID=1000
      - GID=1000
    volumes:
    - data:/data
    - config:/config
    - apps2:/apps2
    ports:
      - 80:80

  db:
    image: mariadb:10
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecretpassword

volumes:
  data:
    driver: local
  config:
    driver: local
  apps2:
    driver: local
  mysql:
    driver: local
